### ISSUE TITLE
Request examples

### ISSUE THREAD

**Issue by simonppg** [mikro-orm/express-js-example-app#3]
Hi thanks for adding this example.

I am tryning to test it but I can't figure it out how to use it correctly.

I was able to POST and new author passing 'user and email' got a status 200 and the saved author, but once I make a GET request to /author, I got nothing, just and empty array.

Could somebody add some request examples to try?

**Comment by simonppg** [comment]
I figure it out what happend, I looks like this author was never save, it only responde like everything is ok.

I changed this line:
`
await DI.authorRepository.persist(author);
`

with:
`
await DI.authorRepository.persistAndFlush(author);
`

**Comment by B4nan** [comment]
Exactly, same issue with the express-ts example app. 

This comes from v2, where `persist` had `flush` parameter that was originally set to `true` by default. In v3 the default changed to `false`, in v4 the `flush` parameter was removed.
